### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by MathieuSoysal** [forax/beautiful_logger#9]
Hello, Thank you for this project, is a good idea.

I wanted to know if is possible to add a bit more examples of the configuration of the logger?

**Comment by forax** [comment]
The configuration is attached to either a class, a package or a module.
The methods `LoggerConfig.fromClass(Example.class)`(respectively `fromPackage`, `fromModule`) let you retrieve and modify the configuration.
There are 4 properties: 'enable' which indicates if the logger is enable globally, 'level' which indicates that the message with at least this level will be issued, 'levelOverride' that overrides the default values of the logger libraries you are using and 'logEventFactory' that let you choose the library you want to use

To update the properties, you can use the method `LoggerConfig.update()` and you can chain the different options.
```java
  loggerConfig.update(upd -> upd.level(...).logFacadeFactory(...));
```

When you create a Logger with Logger.getLogger(Example.class), it first check if there is a configuration for the class if not, it will use the configuration for the package, or if it does not exist the configuration of the module.
(Logger.getLogger() is a convenient method that uses the class calling Logger.getLogger()).

**Comment by forax** [comment]
You have two ways, either you configure the underlying logger to log to a file/stdout or you create a logger that calls your own logging function.

For the later, you can take a look to
  https://github.com/forax/beautiful_logger/blob/master/src/test/java/com/github/forax/beautifullogger/LoggerConfigSupport.java
that create a LogFacadeFactory from a Printer interface.

You can use it with a logger config (so it may applies to several loggers in the same class/package/module)
  ```java
  loggerConfig.update(upd -> upd.logFacadeFactory(LoggerConfigSupport.printer((message, loggerLevel, context) -> {
          ...
  })));
  ```
or when creating a Logger
```java
  Logger logger = Logger.getLogger(
        Example.class,
        upd -> upd.logFacadeFactory(LoggerConfigSupport.printer((message, loggerLevel, context) -> {
          ...
        })));
```

'message' is the string to log, 'loggerLevel' is the level associated with the message and 'context' is the exception if one is provided (null otherwise).
